[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "s1isp"
authors = [
    {name = "Antonio Valentino", email = "antonio.valentino@tiscali.it"},
]
description = "Sentinel-1 Instrument Source Packets decoder"
readme = {file = "README.rst", content-type = "text/x-rst"}
requires-python = ">=3.7"
keywords = [
    "satellite",
    "decoder",
    "isp",
]
license = {text = "Apache-2.0"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Topic :: Utilities",
]
dependencies = [
    'bpack[bs,np]',
]
dynamic = ["version"]


[project.optional-dependencies]
test = ["pytest"]
# docs = ["sphinx", "sphinx_rtd_theme"]


[project.urls]
homepage = "https://github.com/avalentino/s1isp"
# documentation = "https://s1isp.readthedocs.io"
documentation = "https://github.com/avalentino/s1isp/blob/main/README.rst"
repository = "https://github.com/avalentino/s1isp.git"
# changelog = "https://github.com/avalentino/s1isp/blob/main/NEWS.rst"


[tool.setuptools]
packages = ["s1isp"]
zip-safe = true
# license-files = ["LICENSE"]


[tool.setuptools.dynamic]
version = {attr = "s1isp.__version__"}


[tool.pytest.ini_options]
# addopts = "--ignore=examples/"


[tool.black]
line-length = 79
# target-version = ['py311']


[tool.isort]
profile = "black"
length_sort = true
no_inline_sort = true
include_trailing_comma = true
use_parentheses = true
line_length = 79

